project_name: melange

before:
  hooks:
    - go mod download
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

env:
  - COSIGN_YES=true

builds:
  - id: melange-build
    binary: melange
    main: ./
    env:
      - CGO_ENABLED=0
    goos:
      # melange requires alpine, so only build linux binaries.
      - linux
    goarch:
      - "386"
      - amd64
      - arm64
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -extldflags "-static"
      - "{{ .Env.LDFLAGS }}"

signs:
  - id: melange-cosign
    cmd: cosign
    certificate: "${artifact}.crt"
    args: ["sign-blob", "--output-signature", "${signature}", "--output-certificate", "${certificate}", "${artifact}"]
    artifacts: all

archives:
  - files:
      - LICENSE
    wrap_in_directory: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: false
  prerelease: true
  name_template: "Release {{ .Tag }}"
